# pull official base image
FROM node:14-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package*.json ./
RUN npm install --silent
RUN npm install react-scripts -g --silent
RUN yarn add @material-ui/core
RUN npm i install @material-ui/core --save
RUN npm install @material-ui/icons
RUN npm i install @material-ui/lab

# add app
COPY . ./

# start app
CMD ["npm", "start"]