version: '3'

services:
  dashboard-db:
    container_name: dashboard-db
    build: ./db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-tier
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: dashboard
      POSTGRES_PASSWORD: dashboard

  dashboard-server:
    container_name: dashboard-server
    build: ./server
    depends_on:
      - dashboard-db
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-tier
      - back-tier
    env_file:
      - server/server_variables.dev.env

  dashboard-client:
    container_name: dashboard-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - dashboard-server
    restart: always
    volumes:
      - './client:/app:z'
      - '/app/node_modules'
    ports:
      - 3000:3000
    networks:
      - client-tier
      - back-tier
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - client/client_variables.dev.env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    logging:
      driver: none
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - db-tier
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin

networks:
  db-tier:
    driver: bridge
  back-tier:
    driver: bridge
  client-tier:
    driver: bridge

volumes:
  db-data:
  pgadmin:
