version: '3'

services:
  db:
    container_name: db
    image: postgres:12.4
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - db-tier
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: dashboard
      POSTGRES_PASSWORD: dashboard
  server:
    container_name: server
    build: ./server
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-tier
      - back-tier
    env_file:
      - server/server_variables.env
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - './client:/app'
      - './client/app/node_modules'
    ports:
      - 80:80
    networks:
      - client-tier
      - back-tier
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - client/client_variables.env

networks:
  db-tier:
    driver: bridge
  back-tier:
    driver: bridge
  client-tier:
    driver: bridge

volumes:
  db-data: