version: '3'

services:
  dashboard-db:
    container_name: dashboard-db
    build: ./db
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-tier
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: dashboard
      POSTGRES_PASSWORD: dashboard

  dashboard-server:
    container_name: dashboard-server
    build:
      context: ./server
      dockerfile: Dockerfile.test
    depends_on:
      - dashboard-db
    command: sh -c "/wait && mocha -R spec tests/spec.js"
    environment:
      - WAIT_HOSTS=dashboard-db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - 8080:8080
    networks:
      - db-tier
      - back-tier
    env_file:
      - server/server_variables.env

networks:
  db-tier:
    driver: bridge
  back-tier:
    driver: bridge
  client-tier:
    driver: bridge

volumes:
  db-data:
  pgadmin:
