FROM node:14-alpine

# create app directory
WORKDIR /usr/src/app/

ENV NODE_ENV dev

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# build the app
RUN npm install
RUN npm install -g mocha

# Add docker-compose-wait tool -------------------
ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

# Bundle app source
COPY . ./

CMD [ "mocha", "-R", "spec", "tests/spec.js" ]